### ISSUE TITLE
http: TLS handshake error from 172.16.70.41:19289: tls: client offered an unsupported, maximum protocol version of 301

### ISSUE THREAD

**Issue by vmalaga** [tsuru/planb#37]
Hello.

We are running planb on production with 18000 domains with tls and its certificates and keys on redis for more of 3 months and are very satisfied.
But in the last weeks, I am receiving issues from customers about problems seeing our webs from some versions of Internet Explorer.

At the syslog I can see a lot of messages regarding unsupported protocols from clients like these with versions protocol from 300 to 302

`http: TLS handshake error from 172.16.70.41:19289: tls: client offered an unsupported, maximum protocol version of 301`
`http: TLS handshake error from 172.16.70.42:49109: tls: client offered an unsupported, maximum protocol version of 300`
`http: TLS handshake error from 172.16.70.41:19201: tls: client offered an unsupported, maximum protocol version of 302`

at first, I thought it was a problem with the letsencrypt certificates that we are using, but testing the same certificate with haproxy don't fail

I know that the problem is at the client browser but need to ask you if there is any possible solution for this before moving to haproxy, because I prefer planb so it is very flexible and scalable.

Sites that fail with planb and IE - letsencrypt cert
https://www.bardetapassansebastian.com/
https://www.taller-pintura-moto-vigo.com

Sites working with haproxy and IE - letsencrypt cert
https://www.qdqplus.es/MP/petit-marc/
https://www.infoqdq.es/MP/rincon-luis-mari/

**Comment by cezarsa** [comment]
Hi @vmalaga. This is happening because the minimum supported TLS version in planb is TLS 1.2 (0x303), in these error messages 302 is TLS 1.1, 301 is TLS 1.0 and 300 is SSL 3.0. From what I could gather only IE 11+ support TLS 1.2 by default and IE 8-10 support it but it must first be manually enabled in some Internet Options screen.

We have limited ourselves to supporting TLS 1.2 by default because previous TLS versions are now considered insecure and are liable to multiple vulnerabilities. Also we have a limited set of allowed cyphers as many were blacklisted and considered insecure.

It may be possible for us to add configuration flags to allow changing both tls version and allowed cyphers, however I'm not sure if that would be wanted as the server would be less secure this way.

**Comment by cezarsa** [comment]
I've just pushed a fix to this problem by including a new CLI flag `--tls-preset`. Starting planb with `--tls-preset intermediate` should make it compatible with IE7+. The default is `--tls-preset modern`. You can try it on the master branch, please feel free to reopen if this does not fix your problem.

The presets are based on recommendations from https://wiki.mozilla.org/Security/Server_Side_TLS. However, I'm not sure weather the `old` preset will work with IE6 or not due to Go not supporting some cyphers and SSL2.

**Comment by vmalaga** [comment]
Hi @cezarsa thanks a lot for the quick work.
I am going to try it now and inform you if this change mitigate the problem.
In this case, I stay quiet as planb is behind a snort firewall and has rules to prevent attacks by vulnerabilities related to SSL and TLS protocols

Also checking our statistics I don't see that there are accesses with IE6 so no need support for it.

Thanks again

**Comment by vmalaga** [comment]
Hi @cezarsa tested and working fine on IE7 with all our domains.
I don't know how I could thank you for the great work, both in planb and tsuru.

thanks again
